### ISSUE TITLE
Liguagem e Frameworks a serem utilizados - Estudo Individual

### ISSUE THREAD

**Issue by pedrobarbosaocb** [ResidenciaTICBrisa/05_PipelineFinatec#2]
### Descrição
- Estudo de linguagens e frameworks (Ex.: Python, Angular) que mais se adequam ao projeto.

### Tarefas
- [x] Realizar o estudo individual;
- [x] Propor as linguagens e frameworks a serem utilizados.

**Comment by IsaacLusca** [comment]
Listagem das principais linguagens para o contexto de pipeline, desde questões de desempenho e bibliotecas utilizadas

**Comment by raqueleucaria** [comment]
Foi passado para a gitpages
Treinamento -> Estudo individual
