### ISSUE TITLE
Metodologias - Estudo Individual

### ISSUE THREAD

**Issue by pedrobarbosaocb** [ResidenciaTICBrisa/05_PipelineFinatec#3]
### Descrição
- Estudo de metodologias (Ex.: XP, Scrum) que mais se adequam ao projeto.

### Tarefas
- [x] Realizar o estudo individual;
- [x] Propor as metodologias a serem utilizadas.

**Comment by cansancaojennifer** [comment]
Estudo de algumas metodologias: https://docs.google.com/document/d/1BoPRcTD0yqj-_wJ99G1iltqR0MnARAas2wuX-kgXeAI/edit?usp=sharing

**Comment by raqueleucaria** [comment]
Foi passado para o gitpages
Treinamentos -> Estudo individual -> Metodologias
