### ISSUE TITLE
Entrega dos protótipos individuais

### ISSUE THREAD

**Issue by pedrobarbosaocb** [ResidenciaTICBrisa/05_PipelineFinatec#33]
### Descrição
- Na última reunião foi acordado que cada um do grupo ficaria responsável pela criação de um protótipo de papel (rascunho) de como seria a solução. Assim, conseguiremos alinhar o entendimento da interface da solução.

### Tarefas
- [x] Protótipo de papel do Hemanoel
- [x] Protótipo de papel do Isaac
- [x] Protótipo de papel da Jennifer
- [x] Protótipo de papel do Pedro
- [x] Protótipo de papel da Raquel

### Observações
- Com esses protótipos nós discutiremos o que seria mantido e o Isaac juntaria em um protótipo único de baixa fidelidade

**Comment by pedrobarbosaocb** [comment]
| Tela | Descrição |
| --- | --- |
| Login | ![Login](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/78980796/8ce01ca8-3d4a-4207-9120-7406f92bffea) |
| Main | ![Main](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/78980796/7563aafc-181f-4a44-a16d-92c5e32d8889) |
| Financiador | ![Financiador](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/78980796/d674ddb2-6c92-4680-b6a2-696b81a7f224) |
| Projeto | ![Projeto](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/78980796/2aa49ca9-cc1b-48ff-92cc-1cd3476117ce) |

**Comment by hemanoelbritoF** [comment]
![Component 1](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/88113694/c204b5f6-a768-4246-96ef-0308946f7787)

**Comment by raqueleucaria** [comment]
![Protótipo _230814_132931](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/81540491/fe3513b7-50e9-4112-b802-7a861f5d91f2)

**Comment by IsaacLusca** [comment]
![image](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/90662483/1d47493d-bf16-4071-821b-4cd360a1d6a0)
![image](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/90662483/d0fbc28a-c488-41c0-a9b5-8828a32a1df3)
![image](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/90662483/93b192c7-e089-4ed1-ac66-13526ead466f)

**Comment by raqueleucaria** [comment]
Link com a [Gravação da reunião](https://youtu.be/SLZDtI5BATc).

**Comment by cansancaojennifer** [comment]
![1](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/120498502/b50f2316-5494-462f-8ed2-08e284ab37e6)
![2](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/120498502/4e9d4c8b-ca1b-4bdb-b920-cd793676924c)
![3](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/120498502/3df0858e-a811-487e-9ec1-ff05fae88224)
![4](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/120498502/7a208b54-8e32-4f09-9c49-294e4a8baafa)
