### ISSUE TITLE
Pipeline de Dados - Estudo Individual

### ISSUE THREAD

**Issue by pedrobarbosaocb** [ResidenciaTICBrisa/05_PipelineFinatec#4]
### Descrição
- Estudo do funcionamento e criação de Pipelines de Dados.

### Tarefas
- [x] Realizar o estudo individual;
- [x] Comprovar o entendimento do funcionamento de uma Pipeline de Dados.

**Comment by hemanoelbritoF** [comment]
Estudo individual completado, seguindo o tutorial https://www.youtube.com/watch?v=uhQ54Dgp6To&ab_channel=tuplespectra.  

O tutorial consistia em ensinar como construir e automatizar um processo ETL que pudesse extrair dados de uma API de dados meteorológicos, transformá-los  e carregá-los em um bucket S3 usando o Apache Airflow. (O Apache Airflow é uma plataforma de código aberto usada para criar, agendar e monitorar fluxos de trabalho (workflows) de dados. É uma ferramenta popular na área de engenharia de dados e amplamente utilizada para automatizar e orquestrar processos de extração, transformação e carga de dados (ETL), além de outras tarefas relacionadas ao processamento de dados.)

resultado final do tutorial
![Screenshot from 2023-07-26 17-27-04](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/88113694/7ee42ce3-7e46-47c4-8d64-a3f7e30600ae)

Obs:O tutorial teve uma parte limitada, pois o uso dos serviços da Amazon poderia acarretar em utilização de recursos pagos na nuvem, portanto, foi adaptado para funcionar na máquina local.

**Comment by raqueleucaria** [comment]
Foi passado para a gitpages
Treinamento -> Pipeline de Dados
