### ISSUE TITLE
Documentação com MkDocs - Criação do Ambiente

### ISSUE THREAD

**Issue by pedrobarbosaocb** [ResidenciaTICBrisa/05_PipelineFinatec#5]
### Descrição
- Criação do ambiente de documentação com MkDocs

### Tarefas
- [x] Criar o ambiente em MkDocs;
- [x] Gerar o CI para o build automatizado da documentação.

**Comment by raqueleucaria** [comment]
Em outro repositório criei o mkdocs com nossas informações para posteriormente gravar o vídeo de treinamento e colocar no nosso repositótio.

https://raqueleucaria.github.io/teste-mkdocs/

**Comment by raqueleucaria** [comment]
Estou tendo problemas com o ci do deploy, estou procurando soluções para poder finalizar a issue.

**Comment by raqueleucaria** [comment]
Descobri o problema, é preciso dar a permissão de gravação para os workflows nas configurações do repositório.
