### ISSUE TITLE
Protótipo de Alta - Tela de Login

### ISSUE THREAD

**Issue by raqueleucaria** [ResidenciaTICBrisa/05_PipelineFinatec#69]
### Descrição
Criação do protótipo de alta da tela **Login** 

- Épico: #61  
- Feature: Login Usuário
- História de Usuário: [US01]

### Critério de aceitação
- [x] Os campos a serem preenchidos devem ser: Usuário e Senha;

**Comment by pedrobarbosaocb** [comment]
| Titulo | Imagem |
| ---- | ----- |
| Login | ![image](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/78980796/a3effe51-ce6a-4a2f-874b-5c1872117d21) |
| Cadastro | ![image](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/78980796/203e5aa8-bafe-40d8-a187-032a2e02fc23) |
