### ISSUE TITLE
Prototipo de Alta - Tela Inicial

### ISSUE THREAD

**Issue by raqueleucaria** [ResidenciaTICBrisa/05_PipelineFinatec#70]
### Descrição
Criação do protótipo de alta da tela  **Inicial**, onde já é apresentado a **seleção do projeto**

- Épico: #62  
- Feature: Seleção de projeto e Seleção de template
- - História de Usuário: [US02] e [US07]

### Critério de aceitação
- [x] Deve ser possível selecionar o template
- [x] O sistema deve permitir que a busca seja feita por id do projeto;

**Comment by pedrobarbosaocb** [comment]
| Titulo | Imagem |
| ------ | --------- |
| Home | ![image](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/78980796/0bc05e59-b404-4bee-834b-56709fb21500) |
