### ISSUE TITLE
Criação da Tela Inicial

### ISSUE THREAD

**Issue by raqueleucaria** [ResidenciaTICBrisa/05_PipelineFinatec#72]
### Descrição
Criação tela **Inicial** com a seleção de projeto

- Épico: #62 
- Feature: Preenchimento da planilha
- História de Usuário: [US02] e [US07]

### Critério de aceitação
- [x] Deve ser possível selecionar o template
- [x] O sistema deve impedir a seleção do template se o não houver um projeto selecionado;
- [x] O sistema deve possuir uma lista com todos os templates.
- [x] O sistema deve permitir que a busca seja feita por id do projeto;
- [x] O sistema deverá validar os campos de entrada, garantindo que não estejam errados ou vazios, onde:
  - [x] Deverá exibir uma mensagem de erro caso tenha algo errado

**Comment by IsaacLusca** [comment]
https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/90662483/7b03c17a-3fa4-4847-8ce0-758f10b83fda
