### ISSUE TITLE
Ambiente de desenvolvimento

### ISSUE THREAD

**Issue by raqueleucaria** [ResidenciaTICBrisa/05_PipelineFinatec#73]
### Descrição
Preparação do ambiente de desenvolvimento no servidor disponibilizado pela FINATEC.

### Critérios de aceitação
- [x] Adequado com as tecnologias definidas: Python, Django, SQL Serve

**Comment by pedrobarbosaocb** [comment]
Ambiente Django preparado e presente na branch Dev.

Assim que recebermos o acesso ao banco de dados irei fazer a conexão com SQL Server.
