### ISSUE TITLE
Conexão com o banco de dados

### ISSUE THREAD

**Issue by raqueleucaria** [ResidenciaTICBrisa/05_PipelineFinatec#74]
### Descrição
Fazer a conexão com o banco de dados e fazer a requisição dos dados dos projetos

### Critério de aceitação
- [ ] utilizando python e SQL Server
- [ ] fazer apenas a requisição dos dados, sem altera-los
- [ ] conetar fora da rede da FINATEC
- [ ] dados corretos
- [ ] mostrar os dados na aplicação

**Comment by pedrobarbosaocb** [comment]
PR #127 contem a consulta ao banco
