### ISSUE TITLE
Rastreamento e preenchimento da FUB

### ISSUE THREAD

**Issue by raqueleucaria** [ResidenciaTICBrisa/05_PipelineFinatec#75]
### Descrição
Rastreamento das tabelas e preenchimento do template

- Épico: #62 
- Feature: Preenchimento da planilha
- História de Usuário: [US02] e [US07]

### Observações
- [x] Usar o template FUB
- [x] Usar dados do BD da FINATEC (se não tiver disponível, usar dados mocados)

**Comment by hemanoelbritoF** [comment]
planilha preenchida ,com o código para preenchimento dela presente na [dev](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/tree/dev)
![image](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/88113694/cf9590a1-adb0-4150-bd2e-0e2eb0f23c4e)
