### ISSUE TITLE
Protótipo perfil de usuário

### ISSUE THREAD

**Issue by raqueleucaria** [ResidenciaTICBrisa/05_PipelineFinatec#80]
### Descrição
Criação do protótipo da tela **perfil de usuário** e elementos de cadastramento

- Épico: #61
- Feature: Acesso ao sistema
- História de Usuário: [US01] e [US05]

### Critério de aceitação
- Deve seguir o padrão de cores da FINATEC
- Ter as telas de cadastramento e perfil de usuário e administrador já
- Os campos a serem preenchidos devem ser:
    - [x]  usuário;
    - [x]  Senha;
- O sistema deve verificar se a senha está correta e seja associada ao usuário inserido:
    - [ ]  Caso negativo: Exibir mensagem de erro;
    - [ ]  Caso positivo: O usuário deve ser autenticado e direcionado para a tela principal do sistema;
- [ ]  **O sistema deve possuir seu próprio banco de dados em SQL com o cadastro de usuários**
- [ ]  O sistema deve verificar se o usuário inserido está cadastrado no sistema;

**Comment by pedrobarbosaocb** [comment]
![image](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/78980796/cb7bf8d4-daab-42c2-9bac-e5ff32da0638)
