### ISSUE TITLE
Modelagem do Banco de Dados

### ISSUE THREAD

**Issue by raqueleucaria** [ResidenciaTICBrisa/05_PipelineFinatec#82]
### Descrição

Criação do modelo de nosso banco de dados para armazenar informações do sistema.

- Épico: #67
- Feature: Login usuário, login admin, histórico e reportar
- História de Usuário: [US01], [US05], [US12] e [US13]

### Critério de aceitação

- [x]  Em postgreSQL*
- [ ] Criação do diagrama de uso
- [x] Deve apresentar tabelas com usuários, histórico e reportagem
- [x] O banco de dados deve ser conectado a aplicação

**Comment by raqueleucaria** [comment]
![Notes_230829_135007](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/81540491/2e98497a-f618-4206-a103-b7ce78cb3c81)

**Comment by raqueleucaria** [comment]
![image](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/81540491/16710aef-c222-4a2c-8656-aa8e2d231226)

**Comment by raqueleucaria** [comment]
![EX1Aula3 (3)](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/81540491/efe65b43-9ead-4920-b74d-e93bbb981483)

**Comment by raqueleucaria** [comment]
![EX1Aula3 (3)](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/81540491/35d74b85-bccf-4758-879f-ab3cfdcfc04d)

**Estrutura em azul** = Tabela puxada do BD da FINATEC
**Células em vermelho** = dúvida sobre o são esses dados

**Comment by raqueleucaria** [comment]
![EX1Aula3 (5)](https://github.com/ResidenciaTICBrisa/05_PipelineFinatec/assets/81540491/cc4d97a3-9a97-477c-b173-51873519532e)

**Comment by pedrobarbosaocb** [comment]
CODIGO
NOME
SALDO
DATA_ASSINATURA
DATA_VIGENCIA
DATA_ENCERRAMENTO
TIPO_CONTRATO
INSTITUICAO_EXECUTORA
PROCESSO
SUBPROCESSO
COD_PROPOSTA
PROPOSTA
OBJETIVOS
VALOR_APROVADO
NOME_TP_CONTROLE_SALDO
GRUPO_GESTORES
GESTOR_RESP
COORDENADOR
PROCEDIMENTO_COMPRA
TAB_FRETE
TAB_DIARIAS
CUSTO_OP
NOME_FINANCIADOR
DEPARTAMENTO
SITUACAO
BANCO
AGENCIA_BANCARIA
CONTA_BANCARIA
CENTRO_CUSTO
CONTA_CAIXA
CATEGORIA_PROJETO
COD_CONVENIO_CONTA
COD_STATUS
IND_SUB_PROJETO
TIPO_CUSTO_OP
PROJETO_MAE
ID_COORDENADOR
ID_FINANCIADOR
ID_INSTITUICAO
ID_DEPARTAMENTO
NOME_INSTITUICAO
ID_INSTITUICAO_EXECUTORA
ID_TIPO

obs: foi passada uma outra tabela com os nomes das colunas alteradas

**Comment by pedrobarbosaocb** [comment]
Itens da Conveniar

ID_LANCAMENTO
ID_PROJETO
ID_RUBRICA
NOME_RUBRICA
T
ID_TP_LANCAMENTO
TIPO_LANCAMENTO
ID_FAVORECIDO
NOME_FAVORECIDO
CNPJ_FAVORECIDO
TIPO_FAVORECIDO
VALOR_LANCADO
VALOR_PAGO
ID_STATUS
STATUS_LANCAMENTO
FLAG_RECEITA
HIS_LANCAMENTO
NUM_DOC_F
DATA_PAGA
DATA_CRIA
DATA_BAIX
DATA_EMIS
DATA_VENC
ID_LANCAMENTO
ID_PROJETO
ID_RUBRICA
NOME_RUBRICA
T
ID_TP_LANCAMENTO
TIPO_LANCAMENTO
ID_FAVORECIDO
NOME_FAVORECIDO
CNPJ_FAVORECIDO
TIPO_FAVORECIDO
VALOR_LANCADO
VALOR_PAGO
ID_STATUS
STATUS_LANCAMENTO
FLAG_RECEITA
HIS_LANCAMENTO
NUM_DOC_F
DATA_PAGA
DATA_CRIA
DATA_BAIX
DATA_EMIS
DATA_VENC
